[project]
name = "2048"
version = "0.1.0"
description = "A replica of the 2048 game. Future plans to create an AI bot to beat it."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "mgomes", email = ""}
]
dependencies = [
    "numpy>=1.24.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
python-version = "3.12"
